site_name: Donavin Gaming Stuff
nav:
  - Home: index.md
  - Football:
    - Coverages:
      - Identifying the Coverage: football/coverages/identifying_cov.md
      - Attacking the Coverage:
        - Cover 0: football/coverages/attacking_coverages/cover0/cover0.md
        - Cover 1: football/coverages/attacking_coverages/cover1/cover1.md
        - Cover 2: football/coverages/attacking_coverages/cover2/cover2.md
        - Cover 2 Man: football/coverages/attacking_coverages/cover2_man/cover2_man.md
        - Cover 3: football/coverages/attacking_coverages/cover3/cover3.md
        - Cover 4: football/coverages/attacking_coverages/cover4/cover4.md
        - Cover 4 Match: football/coverages/attacking_coverages/cover4_match/cover4_match.md
        - Cover 6: football/coverages/attacking_coverages/cover6/cover6.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
#Push up